DB_HOST: ENC[AES256_GCM,data:cyZSWknHo0Up,iv:fvCFHWttP174iJjukDPDltZTAolwiIzTy1ouAn41OG0=,tag:wqtrCFfN20tLRPTogQlUgA==,type:str]
DB_PORT: ENC[AES256_GCM,data:LufG4g==,iv:NwVJohUQZAMRrSshuphyq1mcmCur3ztOIc8sMZhZ3sI=,tag:GvB2Mia7juKNjrgFCY46bw==,type:int]
DB_USER: ENC[AES256_GCM,data:Fkbz34ji47xq,iv:RIPJCRuDd3Q/qrq2oBB9LzxLiAzkZe7TO3l/rFZKLUw=,tag:132VZI8+F0qHbYtBBtlI/Q==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:bb2WxY13qh6D5v4vfDsVYX57i+HYBXt/Lg==,iv:0E7yGKyglB4AsivPoj+aqmJdUFLoxABM6sNN3k762ho=,tag:Bn07mNHUskhu4zLKbWg83A==,type:str]
DB_NAME: ENC[AES256_GCM,data:2JQ6O60VGu9CiHev4g==,iv:9QJO68yaC+v70fCCYcpQvgFKXlfaWQiU6y42FNwSDE4=,tag:1EPyl7MIeTpYuyd9xOodCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYmFUWGxyVldiZ0Z2YU8x
            a1JKWGpsQ2FJTm9GNHJpUjlwZkpITjFlcXpBCk96eWxwTkV1YWFGcjZjYUxmZ28w
            a0J2V05ZbXhLcG1LYlBXa09NVmV6aU0KLS0tIHRtRUdOdGJ1T2VQZDZHb2ZIK1pG
            ZVBKYnpKdGhHRDJhZmxZcldXYzBEOU0Ke5QQdEU2Erot60u6cP/pGAZJkZYyvjOr
            BSMMoEc0Xjrpa7UlBUtYiJI2MOGNNyElKbIlhSPmXsO0hmUivIBsrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zl42k6w8t258dhmne88akxn7dspj4sltzzpge86cx55mc9xhzcsshurnmy
    lastmodified: "2026-08-08T18:06:35Z"
    mac: ENC[AES256_GCM,data:dPXxFBd9kUfGo5IbUa17n5n6w3EsUkYIMGvZs4Nv3LZdQKQmIKzLLHIikXYxob4ED8HUZBnqoicItOBMJctQoROSoGok1h/g3h3sf5gjGedI4bnKXzj4ZOW0zkmIOccpMZeEL8B/bMXFTQL1V5ByaEYOSL+qqmFcr1nvsbZsl4c=,iv:q3dADIqQYz0mYgruT1nGRpfaQKWZUSmLXHO8QivDVQY=,tag:UCJ+Vep96BLKSoClAFbRLA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
