DB_HOST: ENC[AES256_GCM,data:cyZSWknHo0Up,iv:fvCFHWttP174iJjukDPDltZTAolwiIzTy1ouAn41OG0=,tag:wqtrCFfN20tLRPTogQlUgA==,type:str]
DB_PORT: ENC[AES256_GCM,data:78GU6Q==,iv:g7YnYoGePzSMT2GjM5LkclETDH0bpEXxpK2WbQJZZUQ=,tag:Q1NVrLEM8n5e5k0wZyQ6wg==,type:int]
DB_USER: ENC[AES256_GCM,data:Fkbz34ji47xq,iv:RIPJCRuDd3Q/qrq2oBB9LzxLiAzkZe7TO3l/rFZKLUw=,tag:132VZI8+F0qHbYtBBtlI/Q==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:bb2WxY13qh6D5v4vfDsVYX57i+HYBXt/Lg==,iv:0E7yGKyglB4AsivPoj+aqmJdUFLoxABM6sNN3k762ho=,tag:Bn07mNHUskhu4zLKbWg83A==,type:str]
DB_NAME: ENC[AES256_GCM,data:2JQ6O60VGu9CiHev4g==,iv:9QJO68yaC+v70fCCYcpQvgFKXlfaWQiU6y42FNwSDE4=,tag:1EPyl7MIeTpYuyd9xOodCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYmFUWGxyVldiZ0Z2YU8x
            a1JKWGpsQ2FJTm9GNHJpUjlwZkpITjFlcXpBCk96eWxwTkV1YWFGcjZjYUxmZ28w
            a0J2V05ZbXhLcG1LYlBXa09NVmV6aU0KLS0tIHRtRUdOdGJ1T2VQZDZHb2ZIK1pG
            ZVBKYnpKdGhHRDJhZmxZcldXYzBEOU0Ke5QQdEU2Erot60u6cP/pGAZJkZYyvjOr
            BSMMoEc0Xjrpa7UlBUtYiJI2MOGNNyElKbIlhSPmXsO0hmUivIBsrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zl42k6w8t258dhmne88akxn7dspj4sltzzpge86cx55mc9xhzcsshurnmy
    lastmodified: "2026-08-09T16:43:45Z"
    mac: ENC[AES256_GCM,data:Cy1evjvL13bEmUV9yVnPdRd4mSZWjO4Upwrcj5Ru4/Dut6gia7ZlQlK8dnpXxHyE5IJa6vUpdQVlLWq81gCdoXLUGAsINnCRxhDQGjT1d1WwZ67OLdjdnwRYXqAPfK9vX4lhaO9b3ydnbVO8lpqf93GOaUaWJ9Mr7333qJ5C314=,iv:NrH3ELMQnOpeDojbK17kc4vvcQUzfY3JZu3a07+qwxk=,tag:AJ5cWH/upK4djmNhKxfwvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
