DB_HOST: ENC[AES256_GCM,data:roD3rQMFGFAbCKRu,iv:218T1/CsDFuKt5CX4Es9911fq1tGpPmINauj6+JI31g=,tag:su0Zch+5FiF+93XCWXqnkA==,type:str]
DB_PORT: ENC[AES256_GCM,data:78GU6Q==,iv:g7YnYoGePzSMT2GjM5LkclETDH0bpEXxpK2WbQJZZUQ=,tag:Q1NVrLEM8n5e5k0wZyQ6wg==,type:int]
DB_USER: ENC[AES256_GCM,data:Fkbz34ji47xq,iv:RIPJCRuDd3Q/qrq2oBB9LzxLiAzkZe7TO3l/rFZKLUw=,tag:132VZI8+F0qHbYtBBtlI/Q==,type:str]
DB_PASSWORD: ENC[AES256_GCM,data:bb2WxY13qh6D5v4vfDsVYX57i+HYBXt/Lg==,iv:0E7yGKyglB4AsivPoj+aqmJdUFLoxABM6sNN3k762ho=,tag:Bn07mNHUskhu4zLKbWg83A==,type:str]
DB_NAME: ENC[AES256_GCM,data:2JQ6O60VGu9CiHev4g==,iv:9QJO68yaC+v70fCCYcpQvgFKXlfaWQiU6y42FNwSDE4=,tag:1EPyl7MIeTpYuyd9xOodCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYmFUWGxyVldiZ0Z2YU8x
            a1JKWGpsQ2FJTm9GNHJpUjlwZkpITjFlcXpBCk96eWxwTkV1YWFGcjZjYUxmZ28w
            a0J2V05ZbXhLcG1LYlBXa09NVmV6aU0KLS0tIHRtRUdOdGJ1T2VQZDZHb2ZIK1pG
            ZVBKYnpKdGhHRDJhZmxZcldXYzBEOU0Ke5QQdEU2Erot60u6cP/pGAZJkZYyvjOr
            BSMMoEc0Xjrpa7UlBUtYiJI2MOGNNyElKbIlhSPmXsO0hmUivIBsrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zl42k6w8t258dhmne88akxn7dspj4sltzzpge86cx55mc9xhzcsshurnmy
    lastmodified: "2026-08-11T15:33:10Z"
    mac: ENC[AES256_GCM,data:JpPqMN2PKHf9FrVFL72xdeWq1h53ssv0KfBFv+lOIZFY9X8bDBZiFPuBOZTU31w7u4seZSqslJutoDvE1/MG5887+xKfqD2mM93XiZkJ2PuZLIEw2ZASi5F4l/8ibRkw3JU+901NdEyNdSsjq0/PLGBDYD/eIf86cGhGW/fDgSc=,iv:6fMAsIKuMneUnjLg5kaHEnk/4xCWXNI7ygbMR5Wt79M=,tag:bau0+XkNZRnji5L+PEPTQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
