sonar.organization=Zeeward41
sonar.projectKey=Zeeward41_Zeewordle
sonar.projectName=Zeewordle

# The paths to the code and tests
sonar.sources=src

# We tell SonarQube which files in src are tests
sonar.tests=src/tests

## We ask SonarQube to ignore these files in the analysis of the main source code
sonar.exclusions=src/tests/**, node_modules/**

# Tell SonarQube where to find the Vitest test coverage report to display the percentage of tested code
sonar.javascript.lcov.reportPaths=coverage/lcov.info
