FROM node:26-alpine AS builder
WORKDIR /app
RUN apk update && apk upgrade --no-cache openssl
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM node:26-alpine
WORKDIR /app
RUN apk update && apk upgrade --no-cache openssl
RUN npm install -g serve
COPY --chown=node:node --from=builder /app/dist ./dist
COPY --chown=node:node entrypoint.sh .
RUN chmod +x ./entrypoint.sh
USER node
EXPOSE 3000
CMD ["./entrypoint.sh"]
