FROM node:26-alpine AS builder
WORKDIR /app
RUN apk update && apk upgrade --no-cache openssl
RUN npm install -g pnpm
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM node:26-alpine
WORKDIR /app
RUN apk update && apk upgrade --no-cache openssl
COPY --from=builder /app/package.json /app/pnpm-lock.yaml ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/api ./api
RUN mkdir -p ./config \
    && rm -rf /usr/local/lib/node_modules/npm /usr/local/bin/npm /usr/local/bin/npx /usr/local/bin/corepack
USER node
EXPOSE 5000
CMD ["node", "dist/server.js"]
