---
- name: Install and configure Nginx
  hosts: role_monitoring_proxy
  gather_facts: true
  become: true
  tasks:

    - name: Installation nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Configure nginx
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        owner: root
        group: root
      notify: 'Restart nginx'

    - name: Ensure nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: 'Restart nginx'
      ansible.builtin.service:
        name: nginx
        state: restarted
