---
plugin: amazon.aws.aws_ec2
regions:
  - eu-west-3

filters:
  tag:Environnement: showcase

keyed_groups:
  - key: ec2_tags.Environnement
    prefix: env
  - key: ec2_tags.Role
    prefix: role

hostnames:
  - instance-id
