openapi: 3.1.2
info:
    title: Zeewordle API documentation.
    version: '0.1'
    description: |
        "Zeewordle API...
    contact:
        name: 'Zeeward41'
        email: 'zeeward41@gmail.com'
servers:
    - url: 'http://localhost:8080/v1'
      description: 'Local development server'
    - url: 'https://dev.xxx.com/v1'
      description: 'Development / Staging server'
    - url: 'https://api.xxx.com/v1'
      description: 'Production server'
tags:
    - name: Authentication
      description: 'Endpoints...'
security:
    - SessionAuth: []
paths:
    /auth/login:
        $ref: "./paths/authLogin.yaml"
components:
    securitySchemes:
        $ref: "./components/securitySchemes.yaml"
    schemas:
        LoginRequest:
            $ref: "./components/schemas/loginRequest.yaml"
        User:
            $ref: "./components/schemas/user.yaml"
        ErrorResponse:
            $ref: "./components/schemas/errorResponse.yaml"
    responses:
        LoginSuccess:
            $ref: "./components/responses/authResponses.yaml#/loginSuccess"
        LoginUnauthorized:
            $ref: "./components/responses/authResponses.yaml#/loginUnauthorized"
        LoginServerError:
            $ref: "./components/responses/authResponses.yaml#/loginServerError"
