/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApiDocRouteImport } from './routes/api-doc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersProfileRouteImport } from './routes/users/profile'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const ApiDocRoute = ApiDocRouteImport.update({
  id: '/api-doc',
  path: '/api-doc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersProfileRoute = UsersProfileRouteImport.update({
  id: '/users/profile',
  path: '/users/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-doc': typeof ApiDocRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/users/profile': typeof UsersProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-doc': typeof ApiDocRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/users/profile': typeof UsersProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-doc': typeof ApiDocRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/users/profile': typeof UsersProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-doc'
    | '/auth/login'
    | '/auth/register'
    | '/users/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api-doc' | '/auth/login' | '/auth/register' | '/users/profile'
  id:
    | '__root__'
    | '/'
    | '/api-doc'
    | '/auth/login'
    | '/auth/register'
    | '/users/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocRoute: typeof ApiDocRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  UsersProfileRoute: typeof UsersProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api-doc': {
      id: '/api-doc'
      path: '/api-doc'
      fullPath: '/api-doc'
      preLoaderRoute: typeof ApiDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/profile': {
      id: '/users/profile'
      path: '/users/profile'
      fullPath: '/users/profile'
      preLoaderRoute: typeof UsersProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocRoute: ApiDocRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  UsersProfileRoute: UsersProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
