name: CD
env:
  REGION: 'eu-west-3'
  SOPS_VERSION: '3.13.3'
on:
  workflow_dispatch:
jobs:
  provision-infrastructure:
    permissions:
      contents: read
      id-token: write # mandatory for oidc
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::585355206799:role/Zeeworlde_github-actions-infrastructure-role
          aws-region: ${{ env.REGION }}

      - name: Install AWS Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb
          rm session-manager-plugin.deb

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Install SOPS and age
        run: |
          # Age installation
          sudo apt update && sudo apt install -y age yq

          # Sops Installation
          curl -LO https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
          sudo mv sops-v${SOPS_VERSION}.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops

      - name: Fetch age key & Decrypt Terraform vars and Backend config files
        run: |
          # 1. get age key
          export SOPS_AGE_KEY=$(aws ssm get-parameter \
            --name "/zeewordle/secrets/age_private_key" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          # 2. env.auto.tfvars
          sops -d infra/terraform/showcase/env.enc.tfvars > infra/terraform/showcase/env.auto.tfvars

          # 3. Backend files
          sops -d apps/backend/config/db.enc.yaml > apps/backend/config/db.yaml
          sops -d apps/backend/config/development.enc.env > apps/backend/config/development.env

          # 4. Convert db.yaml > db.env
          yq -r 'to_entries[] | "\(.key)=\(.value)"' apps/backend/config/db.yaml > apps/backend/config/db.env

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.15.8'

      - name: Terraform Init & Apply
        working-directory: infra/terraform/showcase
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Copy public key in runner
        working-directory: infra/terraform/showcase
        run: |
          mkdir -p ~/.ssh
          cp ansible_ssh_over_ssm ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Config ssh
        run: |
          cat << EOF >> ~/.ssh/config
          Host i-* mi-*
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ProxyCommand sh -c "aws ssm start-session --region ${{ env.REGION }} --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
          EOF
          
          chmod 600 ~/.ssh/config

          ## DEBUG
          cat ~/.ssh/config
          

      - name: Wait for EC2 & SSM initialization
        run: sleep 120

      - name: Install Ansible requirements
        working-directory: infra/ansible
        run: |
          ansible-galaxy install -r requirements.yaml


      - name: Fetch Postgres credentials from AWS Parameter Store
        run: |
          POSTGRES_PASSWORD_HASH=$(aws ssm get-parameter --name "/zeewordle/secrets/postgresPasswordHash" --with-decryption --query "Parameter.Value" --output text)
          POSTGRES_EMAIL=$(aws ssm get-parameter --name "/zeewordle/secrets/postgresEmail" --with-decryption --query "Parameter.Value" --output text)
          GRAFANA_ADMIN_USER=$(aws ssm get-parameter --name "/zeewordle/secrets/grafanaUser" --with-decryption --query "Parameter.Value" --output text)
          GRAFANA_ADMIN_PASSWORD=$(aws ssm get-parameter --name "/zeewordle/secrets/grafanaPassword" --with-decryption --query "Parameter.Value" --output text)

          # Mask sensitive values in GitHub Actions logs
          echo "::add-mask::$POSTGRES_PASSWORD_HASH"
          echo "::add-mask::$POSTGRES_EMAIL"
          echo "::add-mask::$GRAFANA_ADMIN_USER"
          echo "::add-mask::$GRAFANA_ADMIN_PASSWORD"

          # Export as environment variables for later steps
          echo "POSTGRES_PASSWORD_HASH=$POSTGRES_PASSWORD_HASH" >> $GITHUB_ENV
          echo "POSTGRES_EMAIL=$POSTGRES_EMAIL" >> $GITHUB_ENV
          echo "GRAFANA_ADMIN_USER=$GRAFANA_ADMIN_USER" >> $GITHUB_ENV
          echo "GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD" >> $GITHUB_ENV

      - name: Install common setup
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml common_setup.yaml

      - name: Install monitoring setup
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml playbook_monitoring.yaml
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml playbook_nginx.yaml
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml playbook_grafana.yaml



      - name: Install app setup
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml playbook_app.yaml \
            --extra-vars "db_vars_initial_hash='$POSTGRES_PASSWORD_HASH' db_vars_initial_email='$POSTGRES_EMAIL'"

      - name: Cleanup secrets
        if: always()
        run: |
          rm -f infra/terraform/showcase/env.auto.tfvars
          rm -f apps/backend/config/*
