name: CD
env:
  REGION: 'eu-west-3'
  SOPS_VERSION: '3.13.3'
on:
  workflow_dispatch:
jobs:
  provision-infrastructure:
    permissions:
      contents: read
      id-token: write # mandatory for oidc
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::585355206799:role/Zeeworlde_github-actions-infrastructure-role
          aws-region: ${{ env.REGION }}

      - name: Install AWS Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb
          rm session-manager-plugin.deb

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Install SOPS and age
        run: |
          # Age installation
          sudo apt update && sudo apt install -y age

          # Sops Installation
          curl -LO https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
          sudo mv sops-v${SOPS_VERSION}.linux.amd64 /usr/local/bin/sops
          sudo chmod +x /usr/local/bin/sops

      - name: Fetch age key & Decrypt Terraform vars and Backend config files
        run: |
          # 1. get age key
          export SOPS_AGE_KEY=$(aws ssm get-parameter \
            --name "/zeewordle/secrets/age_private_key" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          # 2. env.auto.tfvars
          sops -d infra/terraform/showcase/env.enc.tfvars > infra/terraform/showcase/env.auto.tfvars

          # 3. Backend files
          sops -d apps/backend/config/db.enc.yaml > apps/backend/config/db.yaml
          sops -d apps/backend/development.enc.env > apps/backend/config/development.env

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.15.8'

      - name: Terraform Init & Apply
        working-directory: infra/terraform/showcase
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Copy public key in runner
        working-directory: infra/terraform/showcase
        run: |
          mkdir -p ~/.ssh
          cp ansible_ssh_over_ssm ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Config ssh
        run: |
          cat << EOF >> ~/.ssh/config
          Host i-* mi-*
            User ubuntu
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ProxyCommand sh -c "aws ssm start-session --region ${{ env.REGION }} --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'"
          EOF
          
          chmod 600 ~/.ssh/config

          ## DEBUG
          cat ~/.ssh/config
          

      - name: Wait for EC2 & SSM initialization
        run: sleep 120

      - name: Install Ansible requirements
        working-directory: infra/ansible
        run: |
          ansible-galaxy install -r requirements.yaml

      - name: Install common setup
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml common_setup.yaml

      - name: Install monitoring setup
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml playbook_monitoring.yaml

      - name: Install app setup
        working-directory: infra/ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i inventories/showcase/inv_aws_ec2.yml playbook_app.yaml

      - name: Cleanup secrets
        if: always()
        run: rm -f infra/terraform/showcase/env.auto.tfvars
