---
name: CI
# Global Variables
env:
  BETTERLEAKS_URL: 'https://github.com/betterleaks/betterleaks/releases/download/v1.3.1/betterleaks_1.3.1_linux_x64.tar.gz'
  BETTERLEAKS_CHECKSUM: '7b241c80204538cbb210c94514dc7cdff86430938bd7d5b6e289207959530849'
  BETTERLEAKS_ARCHIVE_NAME: 'betterleaks_1.3.1_linux_x64.tar.gz'
on:
  push:
  workflow_dispatch:
jobs:
  settings-CI: #JOB Name
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v6

      - name: Install and setup Betterleaks (1.3.1)
        run: |
          # 1. Download Betterleaks archive
          curl -sLO ${{ env.BETTERLEAKS_URL }}
          # Check if Archive has been well downloaded
          echo "${{env.BETTERLEAKS_CHECKSUM }} ${{ env.BETTERLEAKS_ARCHIVE_NAME}}" | sha256sum -c
          # untar the archive in betterleaks folder
          tar xzvf ${{ env.BETTERLEAKS_ARCHIVE_NAME }}
          # Move betterleaks to /usr/local/bin
          sudo mv betterleaks /usr/local/bin/
          #Test if betterleaks works
          betterleaks -v

      - name: Check if credentials leaks with betterleaks
        run: |
          # scan the repo with betterleaks
          betterleaks git ${{ github.workspace }} -v --git-workers=4



