name: CI
# Global Variables
env:
  BETTERLEAKS_URL: 'https://github.com/betterleaks/betterleaks/releases/download/v1.3.1/betterleaks_1.3.1_linux_x64.tar.gz'
  BETTERLEAKS_CHECKSUM: '7b241c80204538cbb210c94514dc7cdff86430938bd7d5b6e289207959530849'
  BETTERLEAKS_ARCHIVE_NAME: 'betterleaks_1.3.1_linux_x64.tar.gz'
  PNPM_VERSION: '11.2.2'
  NODE_VERSION: '25.0.0'
  REGION: 'eu-west-3'
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  check-credentials-leak:
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v6

      - name: Install and setup Betterleaks (1.3.1)
        run: |
          # 1. Download Betterleaks archive
          curl -sLO ${{ env.BETTERLEAKS_URL }}
          # Check if Archive has been well downloaded
          echo "${{env.BETTERLEAKS_CHECKSUM }} ${{ env.BETTERLEAKS_ARCHIVE_NAME}}" | sha256sum -c
          # untar the archive in betterleaks folder
          tar xzvf ${{ env.BETTERLEAKS_ARCHIVE_NAME }}
          # Move betterleaks to /usr/local/bin
          sudo mv betterleaks /usr/local/bin/
          #Test if betterleaks works
          betterleaks -v

      - name: Check if credentials leaks with betterleaks
        run: |
          # scan the repo with betterleaks
          betterleaks git ${{ github.workspace }} -v --git-workers=4


  detect-Change:
    runs-on: ubuntu-latest
    needs: check-credentials-leak # Only run this job if check-credentials-leak succeeds
    outputs:
      changes: ${{steps.detect-paths.outputs.changes }} # Store the detected path changes as a JSON array
    steps:
      - name: Get the source code
        uses: actions/checkout@v6
      - name: Get path
        uses: dorny/paths-filter@v4
        id: detect-paths
        with:
          # Base = the previous state of the branch on GitHub before the push
          base: ${{ github.event.before }}
          # ref = the latest commit of the current push
          ref: ${{ github.event.after }}
          filters: |
            frontend:
              - 'apps/frontend/**'
            backend:
              - 'apps/backend/**'

  settings-CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # Required to read the code and SBOM
      actions: read             # Required by SBOM
      security-events: write   # REQUIRED to upload the SARIF report
      id-token: write # mandatory for oidc
    defaults:
      run:
        # Make sure we run command in the right directory
        working-directory: apps/${{ matrix.changes }}

    # Only run if the previous job detected relevant file changes
    #if: ${{ needs.detect-Change.outputs.changes != '[]' && needs.detect-Change.outputs.changes != '' }} 🐼
    needs: detect-Change
    strategy:
      # Dynamically spawn parallel jobs for each modified application
      matrix:
        #changes: ${{ fromJSON(needs.detect-Change.outputs.changes) }} 🐼
        changes: ['frontend', 'backend']
    steps:
      - name: Get the source code
        uses: actions/checkout@v6

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::585355206799:role/Zeeworlde_github-actions-infrastructure-role
          aws-region: ${{ env.REGION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm' # Caches the pnpm global store to speed up subsequent CI runs
          # Tells the cache action where to find the lockfile inside the matrix app directory
          cache-dependency-path: apps/${{ matrix.changes }}/pnpm-lock.yaml

      - name: Install dependency
        run: |
          # Install dependency
          pnpm i --frozen-lockfile # ensure the exact version of dependencies

      - name: Linter & Formatter
        run: |
          ## Formatter
          pnpm run format
          ## Linter
          pnpm run lint

      - name: Unit Test
        run: |
          ## Unit Test
          pnpm run test

      - name: Mutation Testing
        if: ${{ matrix.changes == 'backend' }}
        run: |
          pnpm run test:mutation

      - name: Upload Mutation Report Artifact
        uses: actions/upload-artifact@v7
        if: ${{ matrix.changes == 'backend'}}
        with:
          name: stryker-mutation-report
          path: reports/mutation/mutation.html
          retention-days: 10

      # - name: Run SonarQube Analysis
      #   uses: sonarsource/sonarqube-scan-action@v8.1.0
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONARQUBECLOUD_TOKEN }}
      #   with:
      #     projectBaseDir: apps/${{ matrix.changes }}
      #     args: |
      #       -Dsonar.projectKey=${{ vars.KEY_PROJECT }}_${{ matrix.changes }}
      #       -Dsonar.organization=zeeward41
      #       -Dsonar.projectName=Zeewordle-${{ matrix.changes }}
      #       -Dsonar.sources=src
      #       -Dsonar.tests=src/tests
      #       -Dsonar.exclusions=src/tests/**
      #       -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      #       -Dsonar.qualitygate.wait=true
      #       -Dsonar.qualitygate.timeout=150
      #       -Dsonar.branch.name=main

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results-${{ matrix.changes }}.sarif'
          severity: 'MEDIUM,HIGH,CRITICAL'
          version: 'v0.70.0'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results-${{ matrix.changes }}.sarif'
          category: '${{ matrix.changes }}'

      - name: Run SBOM scan (And upload on Github for dependency graph)
        uses: anchore/sbom-action@v0
        with:
          dependency-snapshot: true
          artifact-name: 'sbom-${{ matrix.changes }}.spdx.json'
          path: .

      - name: Fetch secrets from AWS Parameter Store
        run: |
          # 1. Get Secrets
          NVD_KEY=$(aws ssm get-parameter \
            --name "/zeewordle/secrets/nvd_api_key" \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          # 2. Masquage dans les logs de GitHub Actions
          echo "::add-mask::$NVD_KEY"

          # 3. Export to environment variables for subsequent steps
          echo "NVD_API_KEY=$NVD_KEY" >> $GITHUB_ENV

      - name: Get current date
        id: get-date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Cache NVD Database
        uses: actions/cache@v6
        with:
          path: ${{ github.workspace }}/data
          key: dependency-check-nvd-${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: |
            dependency-check-nvd-${{ runner.os }}-

      - name: OWASP Dependency-Check Scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Zeewordle-${{ matrix.changes }}'
          path: '.'
          format: 'SARIF'
          out: 'reports'
          args: >-
            --nvdApiKey ${{ env.NVD_API_KEY }}
            --data ${{ github/workspace }}/data

      - name: Upload OWASP SARIF result to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'reports/dependency-check-report.sarif'
          category: 'owasp-${{ matrix.changes }}'
