name: Destroy_CD
env:
  REGION: 'eu-west-3'
on:
  workflow_dispatch:
jobs:
  destroy-infrastructure:
    permissions:
      contents: read
      id-token: write # mandatory for oidc
    runs-on: ubuntu-latest

    steps:
      - name: Get the source code
        uses: actions/checkout@v6


      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::585355206799:role/Zeeworlde_github-actions-infrastructure-role
          aws-region: ${{ env.REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.15.8'

      - name: Terraform Destroy
        working-directory: infra/terraform/showcase
        run: |
          terraform init
          terraform destroy -auto-approve

